FROM openjdk:21

WORKDIR /app

# 复制Maven文件
COPY pom.xml ./
COPY .mvn .mvn
COPY mvnw ./

# 给mvnw执行权限
RUN chmod +x mvnw

# 下载依赖
RUN ./mvnw dependency:go-offline -B

# 复制源代码
COPY src ./src

# 构建应用
RUN ./mvnw clean package -DskipTests

# 运行应用
EXPOSE 8080
CMD ["java", "-jar", "target/demo-0.0.1-SNAPSHOT.jar"]